import turtle
from drawShapes import *

t = turtle.Turtle()
squareLength = 36
drawPolygon(t, squareLength, 4)
t.forward(squareLength)
drawFilledPolygon(t, squareLength, 4)
t.right(90)
t.forward(squareLength)
drawFilledPolygon(t, squareLength, 4)
t.left(90)
drawPolygon(t, squareLength, 4)
t.forward(squareLength)
t.left(90)
t.forward(squareLength)
t.right(90)
t.penup()
t.forward(squareLength)
t.forward(squareLength)
t.pendown()
drawFilledPolygon(t, squareLength, 3)
t.right(60)
drawPolygon(t, squareLength, 3)
t.right(60)
drawFilledPolygon(t, squareLength, 3)
t.forward(squareLength)
t.left(60)
t.left(60)
drawFilledPolygon(t, squareLength, 3)
t.forward(squareLength)
t.left(60)
t.penup()
t.forward(squareLength)
t.right(60)
t.forward(squareLength)
t.pendown()
drawPolygon(t, squareLength, 5)
t.forward(squareLength * 0.52)
t.right(30)
drawFilledPolygon(t, squareLength * 0.77, 5)

turtle.exitonclick()